services:
  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  backend:
    build: .
    ports:
      - "8000:8000"
    env_file:
     - .env
    environment:
     - QDRANT_URL=http://qdrant:6333
     - REDIS_URL=redis://redis:6379
    depends_on:
     - redis
     - qdrant

  frontend:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3000"
    command: python -m http.server 3000
    depends_on:
      - backend

volumes:
  qdrant_data:
  redis_data:
    driver: local
